version: '3.8'

services:
  app:
    build: ./docker/.
    container_name: laravel12-skeleton
    ports:
      - "8020:9000"
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - ./laravel:/var/www/laravel
    depends_on:
      db:
        condition: service_healthy
    networks:
      - laravelSkeleton
    #command: sh -c "composer install && php artisan serve --host=0.0.0.0 --port=9000"
    command: sh -c "composer install && php artisan octane:start --server=swoole --host=0.0.0.0 --port=9000"

  app-frontend:
    build: ./docker/.
    container_name: laravel12-skeleton-frontend
    ports:
      - "8080:9000"
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - ./laravel:/var/www/laravel
    depends_on:
      db:
        condition: service_healthy
    networks:
      - laravelSkeleton
    command: sh -c "composer install && php artisan serve --host=0.0.0.0 --port=9000"

  queue:
    build: ./docker/.
    container_name: laravel12-queue
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - ./laravel:/var/www/laravel
    depends_on:
      db:
        condition: service_healthy
    networks:
      - laravelSkeleton
    command: sh -c "php artisan queue:work --queue=emails,default" 

  scheduler:
    build: ./docker/.
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - ./laravel:/var/www/laravel
    command: >
      sh -c "while true;
      do
        php artisan schedule:run --no-interaction;
        sleep 60;
      done"
    depends_on:
      - db
    networks:
      - laravelSkeleton

  db:
    image: mysql:8.0
    container_name: laravel12-skeleton-db
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
      TZ: America/Sao_Paulo
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - laravelSkeleton

  redis:
    image: redis:7-alpine
    container_name: redis-laravel-skeleton
    command: ["redis-server", "--requirepass", "bananinha123"]
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "sh", "-c", "redis-cli -a bananinha123 PING || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - laravelSkeleton

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686" # UI do Jaeger
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
    environment:
      - TZ=America/Sao_Paulo
    networks:
      - laravelSkeleton

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - ./docker/otel-collector:/etc/otel-collector/
    command: ["--config=/etc/otel-collector/config.yaml"]
    depends_on:
      - jaeger
    networks:
      - laravelSkeleton

networks:
  laravelSkeleton:
    driver: bridge