version: '3.8'

services:
  app:
    build: .
    container_name: laravel12-skeleton
    ports:
      - "8020:9000"
    volumes:
      - ./laravel:/var/www/laravel
    depends_on:
      - db
    networks:
      - laravelSkeleton
    #command: sh -c "composer install && php artisan serve --host=0.0.0.0 --port=9000"
    command: sh -c "composer install && php artisan octane:start --server=swoole --host=0.0.0.0 --port=9000"

  queue:
    build: .
    container_name: laravel12-queue
    volumes:
      - ./laravel:/var/www/laravel
    depends_on:
      - db
    networks:
      - laravelSkeleton
    command: sh -c "php artisan queue:work --queue=emails,default" 

  scheduler:
    build: .
    volumes:
      - ./laravel:/var/www/laravel
    command: >
      sh -c "while true;
      do
        php artisan schedule:run --no-interaction;
        sleep 60;
      done"
    networks:
      - laravelSkeleton

  db:
    image: mysql:8.0
    container_name: laravel12-skeleton-db
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
    ports:
      - "3306:3306"
    networks:
      - laravelSkeleton

  redis:
    image: redis:7-alpine
    container_name: redis-laravel-skeleton
    command: ["redis-server", "--requirepass", "bananinha123"]
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "sh", "-c", "redis-cli -a bananinha123 PING || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - laravelSkeleton

networks:
  laravelSkeleton:
    driver: bridge